DROP TABLE IF EXISTS BOOKS_AUD;
CREATE TABLE BOOKS_AUD(
	EVENT_ID INT(11) NOT NULL AUTO_INCREMENT,
    EVENT_DATE DATETIME NOT NULL,
    EVENT_TYPE VARCHAR(10) DEFAULT NULL,
    BOOK_ID INT(11) NOT NULL,
    OLD_TITLE_ID VARCHAR(255),
    NEW_TITLE_ID VARCHAR(255),
    OLD_PUBYEAR INT(4),
    NEW_PUBYEAR INT(4),    
    PRIMARY KEY (`EVENT_ID`)   
);