USE kodilla_course;
SET GLOBAL EVENT_SCHEDULER = ON;
DROP TABLE IF EXISTS STATS;


CREATE TABLE STATS (
	STAT_ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    STAT_DATE DATETIME NOT NULL,
    STAT VARCHAR(20) NOT NULL,
    VALUE INT(11) NOT NULL
);
COMMIT;

USE kodilla_course;
DROP VIEW IF EXISTS BESTSELLERS_COUNT;

CREATE VIEW BESTSELLERS_COUNT AS 
SELECT COUNT(*) BESTSELLERS_COUNT FROM BOOKS WHERE BESTSELLER = 1;

COMMIT;

USE kodilla_course;
DROP EVENT IF EXISTS UPDATE_STATS;

DELIMITER $$

CREATE EVENT UPDATE_STATS
	ON SCHEDULE EVERY 1 MINUTE
	DO
		BEGIN
		DECLARE bestcount int;
		CALL UpdateBestseller();    
		SELECT * FROM BESTSELLERS_COUNT INTO bestcount;
		INSERT INTO STATS (STAT_DATE, STAT, VALUE) VALUES (NOW(),"BESTSELLER",bestcount);
		END $$
    
DELIMITER ;