DROP FUNCTION IF EXISTS IncludesBestseller;

DELIMITER $$

CREATE FUNCTION IncludesBestseller() RETURNS INT DETERMINISTIC
BEGIN
	DECLARE RESULT INT;
	SELECT COUNT(*) FROM information_schema.COLUMNS
    WHERE COLUMN_NAME = 'BESTSELLER'
    AND TABLE_NAME = 'BOOKS' INTO RESULT;
    RETURN RESULT;
END $$

DELIMITER $$