DROP PROCEDURE IF EXISTS UpdateBestsellers;
CALL AddBestsellerCol();


DELIMITER $$

CREATE PROCEDURE UpdateBestsellers()
BEGIN
    DECLARE RENTED_NO, BKS_ID INT;
    DECLARE FINISHED INT DEFAULT 0;
	DECLARE ALL_BOOKS CURSOR FOR SELECT BOOK_ID FROM BOOKS;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET FINISHED=1;
    OPEN ALL_BOOKS;
    WHILE (FINISHED = 0) DO
	FETCH ALL_BOOKS INTO BKS_ID;
        IF (FINISHED = 0) THEN
			SELECT COUNT(*) FROM RENTS
            WHERE (RENT_DATE >= DATE(DATE_SUB(now(), INTERVAL 30 DAY)))
			AND BOOK_ID = BKS_ID
            INTO RENTED_NO;
            IF (RENTED_NO >2) THEN
				UPDATE BOOKS SET BESTSELLER = TRUE
                WHERE BOOK_ID = BKS_ID;
                COMMIT;
			ELSE
				UPDATE BOOKS SET BESTSELLER = FALSE
                WHERE BOOK_ID = BKS_ID;
				COMMIT;
			END IF;
		END IF;
	END WHILE;
    CLOSE ALL_BOOKS;
      
END $$

DELIMITER ;
