DROP TRIGGER IF EXISTS READERS_DELETE;

DELIMITER $$

CREATE TRIGGER READERS_DELETE AFTER DELETE ON READERS
FOR EACH ROW
BEGIN
	INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READERS_ID)
    VALUES(CURTIME(),"INSERT", OLD.READERS.ID);
END$$

DELIMITER ;S