DROP TRIGGER IF EXISTS BOOKS_DELETE;

DELIMITER $$

CREATE TRIGGER BOOKS_DELETE AFTER DELETE ON BOOKS
FOR EACH ROW
BEGIN
	INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID)
    VALUES(CURTIME(),"INSERT", OLD.BOOK.ID);
END$$

DELIMITER ;